x-env: &x-env
  - DEBUG=True
  - SECRET_KEY=django-insecure-airootheesaethahpoo2EeLahze3wooGh9Ash2zae9ohgiengi
  - DATABASE_URL=postgres://postgres:postgres@db/postgres
  - ALLOWED_HOSTS=localhost

services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app/
    environment: *x-env
    depends_on:
      - db
    command: "./start.sh dev"

  tailwind:
    build:
      context: .
      target: cssbuild
    volumes:
      - ./:/app/
    tty: true

volumes:
  postgres_data:
