# Generated by Django 4.2.7 on 2023-11-06 16:29

import re

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import proboj.bots.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                re.compile("^[-a-zA-Z0-9_]+\\Z"),
                                "Enter a valid “slug” consisting of letters, "
                                "numbers, underscores or hyphens.",
                                "invalid",
                            )
                        ],
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="games.game"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BotVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_enabled", models.BooleanField(default=False)),
                ("is_latest", models.BooleanField(default=False)),
                (
                    "sources",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=proboj.bots.models._bot_version_path,
                    ),
                ),
                (
                    "compiled",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=proboj.bots.models._bot_version_path,
                    ),
                ),
                ("number", models.IntegerField(blank=True, null=True)),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bots.bot"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="bot",
            constraint=models.UniqueConstraint(
                models.F("game"), models.F("name"), name="bot__unique_name"
            ),
        ),
    ]
