# Generated by Django 4.2.7 on 2023-11-11 20:33

from django.db import migrations, models

import proboj.bots.models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="botversion",
            name="language",
            field=models.CharField(
                choices=[("py", "Python"), ("cpp", "C++")], default="py"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="botversion",
            name="secret",
            field=models.CharField(
                default=proboj.bots.models.bot_secret, max_length=32
            ),
        ),
        migrations.AlterField(
            model_name="botversion",
            name="compiled",
            field=models.FileField(
                blank=True, null=True, upload_to=proboj.bots.models.bot_version_compiled
            ),
        ),
        migrations.AlterField(
            model_name="botversion",
            name="sources",
            field=models.FileField(
                blank=True, null=True, upload_to=proboj.bots.models.bot_version_sources
            ),
        ),
    ]
