# Generated by Django 4.2.7 on 2023-11-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_botversion_language_botversion_secret_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='botversion',
            constraint=models.UniqueConstraint(models.F('bot'), models.F('secret'), name='botversion__bot_secret__unique'),
        ),
    ]
