# Generated by Django 4.2.7 on 2023-11-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0003_botversion_botversion__bot_secret__unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="botversion",
            name="compile_log",
            field=models.TextField(blank=True),
        ),
    ]
