# Generated by Django 4.2.7 on 2023-11-13 17:32

import django.core.validators
from django.db import migrations, models

import proboj.bots.models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0004_botversion_compile_log"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="botversion",
            name="is_latest",
        ),
        migrations.AlterField(
            model_name="botversion",
            name="is_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="botversion",
            name="sources",
            field=models.FileField(
                upload_to=proboj.bots.models.bot_version_sources,
                validators=[django.core.validators.FileExtensionValidator(["zip"])],
            ),
        ),
    ]
