# Generated by Django 4.2.7 on 2024-04-30 20:10

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0005_remove_botversion_is_latest_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bot",
            name="name",
            field=models.CharField(
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[-a-zA-Z0-9]+\\Z"),
                        "Neplatné meno bota.",
                        "invalid",
                    )
                ],
            ),
        ),
    ]
