# Generated by Django 4.2.7 on 2023-11-21 08:30

from django.db import migrations, models

import proboj.games.models
import proboj.storage


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="bot_timeout",
            field=models.DecimalField(decimal_places=3, default=1, max_digits=6),
        ),
        migrations.AddField(
            model_name="game",
            name="bundle",
            field=models.FileField(
                blank=True,
                storage=proboj.storage.OverwriteStorage(),
                upload_to=proboj.games.models._game_bundle,
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="bundle_version",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="game",
            name="server",
            field=models.FileField(
                blank=True,
                storage=proboj.storage.OverwriteStorage(),
                upload_to=proboj.games.models._game_server,
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="server_version",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
