# Generated by Django 4.2.7 on 2023-11-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0002_game_bot_timeout_game_bundle_game_bundle_version_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="auto_play",
            field=models.IntegerField(default=0),
        ),
    ]
