# Generated by Django 4.2.7 on 2023-11-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_game_auto_play"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="max_bots",
            field=models.IntegerField(default=0),
        ),
    ]
