# Generated by Django 4.2.7 on 2023-11-27 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0004_game_max_bots"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="bot_timeout",
        ),
    ]
