# Generated by Django 4.2.7 on 2023-11-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0005_remove_game_bot_timeout"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="bot_timeout",
            field=models.JSONField(default=dict),
        ),
    ]
