# Generated by Django 4.2.7 on 2024-04-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0008_game_template_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="processes_per_bot",
            field=models.IntegerField(default=1),
        ),
    ]
