# Generated by Django 4.2.7 on 2023-11-18 11:01

from django.db import migrations, models

import proboj.matches.models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="failed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="match",
            name="observer_log",
            field=models.FileField(
                blank=True, upload_to=proboj.matches.models._match_observer_log
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="server_log",
            field=models.FileField(
                blank=True, upload_to=proboj.matches.models._match_server_log
            ),
        ),
        migrations.AddField(
            model_name="matchbot",
            name="log",
            field=models.FileField(
                blank=True, upload_to=proboj.matches.models._match_bot_log
            ),
        ),
    ]
