# Generated by Django 4.2.7 on 2023-11-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0002_match_failed_match_observer_log_match_server_log_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
