name: Build and deploy Docker image

on:
  workflow_dispatch:
    inputs:
      image:
        description: "Image to build"
        required: true
        default: "executor"

env:
  IMAGE_NAME: registry.3sten.sk/proboj-${{ github.event.inputs.image }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@3d58c274f17dffee475a5520cbe67f0a882c4dbb
        with:
          registry: registry.3sten.sk
          username: github
          password: ${{ secrets.DEPLOY_REGISTRY_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@eb539f44b153603ccbfbd98e2ab9d4d0dcaf23a4
        with:
          context: ${{ github.event.inputs.image }}-image
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}
