# Generated by Django 4.2.7 on 2023-11-06 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                ("rules", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-start_at", "-end_at"],
            },
        ),
        migrations.CreateModel(
            name="Configuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("args", models.TextField(blank=True)),
                ("max_bots", models.IntegerField(blank=True, null=True)),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="games.game"
                    ),
                ),
            ],
            options={
                "ordering": ["game", "name"],
            },
        ),
    ]
